# Generated by Django 5.0.1 on 2024-01-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
