# Generated by Django 5.0.1 on 2024-01-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_donor',
            field=models.BooleanField(default=False),
        ),
    ]
